name = "AutoDiff"
uuid = "74297d88-03d1-401d-b49d-baa7bab74246"
authors = ["Will M. Farr <wfarr-vscholar@flatironinstitute.org>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
